create extension if not exists postgis with schema extensions;

create table if not exists public.tornado_tracks (
  id text primary key,
  name text not null,
  date date not null,
  rating text not null,
  states text[] not null default '{}',
  counties text[] not null default '{}',
  wfo text,
  source text not null,
  data_status text not null default 'final',
  path_length_miles numeric,
  max_width_yards integer,
  injuries integer not null default 0,
  fatalities integer not null default 0,
  property_damage_usd numeric not null default 0,
  crop_damage_usd numeric not null default 0,
  begin_time text,
  end_time text,
  source_file text not null,
  source_url text,
  source_row jsonb not null default '{}'::jsonb,
  last_reviewed date,
  narrative text,
  coordinates jsonb not null,
  track geometry(LineString, 4326) not null,
  geometry_quality text not null default 'spc_start_end',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tornado_tracks_date_idx on public.tornado_tracks (date);
create index if not exists tornado_tracks_rating_idx on public.tornado_tracks (rating);
create index if not exists tornado_tracks_source_idx on public.tornado_tracks (source);
create index if not exists tornado_tracks_track_gix on public.tornado_tracks using gist (track);

create table if not exists public.ingestion_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text not null,
  status text not null,
  rows_seen integer not null default 0,
  rows_loaded integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error_message text
);

alter table public.tornado_tracks enable row level security;
alter table public.ingestion_runs enable row level security;

drop policy if exists "Public tornado tracks are readable" on public.tornado_tracks;
create policy "Public tornado tracks are readable"
  on public.tornado_tracks
  for select
  using (true);

create or replace function public.upsert_tornado_tracks(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  item jsonb;
  loaded_count integer := 0;
begin
  for item in select * from jsonb_array_elements(payload)
  loop
    insert into public.tornado_tracks (
      id,
      name,
      date,
      rating,
      states,
      counties,
      wfo,
      source,
      data_status,
      path_length_miles,
      max_width_yards,
      injuries,
      fatalities,
      property_damage_usd,
      crop_damage_usd,
      begin_time,
      end_time,
      source_file,
      source_url,
      source_row,
      last_reviewed,
      narrative,
      coordinates,
      track,
      geometry_quality,
      updated_at
    )
    values (
      item->>'id',
      item->>'name',
      (item->>'date')::date,
      item->>'rating',
      coalesce(array(select jsonb_array_elements_text(item->'states')), array[]::text[]),
      coalesce(array(select jsonb_array_elements_text(item->'counties')), array[]::text[]),
      nullif(item->>'wfo', ''),
      item->>'source',
      item->>'data_status',
      nullif(item->>'path_length_miles', '')::numeric,
      nullif(item->>'max_width_yards', '')::integer,
      coalesce(nullif(item->>'injuries', '')::integer, 0),
      coalesce(nullif(item->>'fatalities', '')::integer, 0),
      coalesce(nullif(item->>'property_damage_usd', '')::numeric, 0),
      coalesce(nullif(item->>'crop_damage_usd', '')::numeric, 0),
      nullif(item->>'begin_time', ''),
      nullif(item->>'end_time', ''),
      item->>'source_file',
      item->>'source_url',
      coalesce(item->'source_row', '{}'::jsonb),
      nullif(item->>'last_reviewed', '')::date,
      nullif(item->>'narrative', ''),
      item->'coordinates',
      st_setsrid(st_geomfromgeojson(jsonb_build_object(
        'type', 'LineString',
        'coordinates', item->'coordinates'
      )::text), 4326),
      coalesce(nullif(item->>'geometry_quality', ''), 'spc_start_end'),
      now()
    )
    on conflict (id) do update set
      name = excluded.name,
      date = excluded.date,
      rating = excluded.rating,
      states = excluded.states,
      counties = excluded.counties,
      wfo = excluded.wfo,
      source = excluded.source,
      data_status = excluded.data_status,
      path_length_miles = excluded.path_length_miles,
      max_width_yards = excluded.max_width_yards,
      injuries = excluded.injuries,
      fatalities = excluded.fatalities,
      property_damage_usd = excluded.property_damage_usd,
      crop_damage_usd = excluded.crop_damage_usd,
      begin_time = excluded.begin_time,
      end_time = excluded.end_time,
      source_file = excluded.source_file,
      source_url = excluded.source_url,
      source_row = excluded.source_row,
      last_reviewed = excluded.last_reviewed,
      narrative = excluded.narrative,
      coordinates = excluded.coordinates,
      track = excluded.track,
      geometry_quality = excluded.geometry_quality,
      updated_at = now();

    loaded_count := loaded_count + 1;
  end loop;

  return loaded_count;
end;
$$;
